### ISSUE TITLE
Facilitate the use of custom grader_flags

### ISSUE THREAD

**Issue by Matistjati** [Kodsport/testdata_tools#16]
If you want to make a problem where you might get 50% of a subtask, you will have to use grader_flags.
Intuitively, it would work something like this:
```
group g1 20
grader_flags arg1=foo arg2=bar
```
However, this wouldn't work easily due to the 'group' command already writing grader_flags to testdata.yaml.
Is anyone aware of an elegant solution to this, or would a rewrite be necessary?

**Comment by simonlindholm** [comment]
The Kattis problem format is moving away from graders, we don't want to encourage use of them in testdata_tools
